package DiseñoDeSistemaAnimado;
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
import slide.sSlide;
/**
 *
 * @author Genarogg
 */
public class DiseñoDeSistemaAnimado extends javax.swing.JFrame {

    /**
     * Creates new form DiseñoDeSistemaAnimado
     */
    sSlide slider;
    public DiseñoDeSistemaAnimado() {
        initComponents();
        this.setLocationRelativeTo(null);
        slider = new sSlide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLoginAbajo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jtxtContraceña = new javax.swing.JPasswordField();
        jBNuevoUsuario = new javax.swing.JButton();
        jBIniciarSecion = new javax.swing.JButton();
        jlLoginAbajo = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLPublicidadSecundaria = new javax.swing.JLabel();
        jLPublicidadPrincipal = new javax.swing.JLabel();
        jLRayabaja = new javax.swing.JLabel();
        jLRayaAlta = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPLoginAbajo.setOpaque(false);
        jPLoginAbajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 174, 2));
        jLabel1.setText("Contraseña:");
        jPLoginAbajo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 20));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(111, 174, 2));
        jLabel2.setText("Usuario:");
        jPLoginAbajo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(19, 19, 19));
        jtxtUsuario.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jtxtUsuario.setText("Nombre:");
        jtxtUsuario.setBorder(null);
        jtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioActionPerformed(evt);
            }
        });
        jPLoginAbajo.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 30));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPLoginAbajo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 10));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPLoginAbajo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 10));

        jtxtContraceña.setBackground(new java.awt.Color(19, 19, 19));
        jtxtContraceña.setText("jPasswordField1");
        jtxtContraceña.setBorder(null);
        jPLoginAbajo.add(jtxtContraceña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 30));

        jBNuevoUsuario.setBackground(new java.awt.Color(255, 102, 0));
        jBNuevoUsuario.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jBNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        jBNuevoUsuario.setText("Sing UP");
        jBNuevoUsuario.setBorder(null);
        jBNuevoUsuario.setBorderPainted(false);
        jBNuevoUsuario.setContentAreaFilled(false);
        jBNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPLoginAbajo.add(jBNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jBIniciarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GO_LOG_ON.png"))); // NOI18N
        jBIniciarSecion.setBorder(null);
        jBIniciarSecion.setBorderPainted(false);
        jBIniciarSecion.setContentAreaFilled(false);
        jBIniciarSecion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBIniciarSecion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GO_LOG_ON.png"))); // NOI18N
        jBIniciarSecion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GO_LOG_ON.png"))); // NOI18N
        jBIniciarSecion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GO_LOG_ON.png"))); // NOI18N
        jBIniciarSecion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBIniciarSecionMouseClicked(evt);
            }
        });
        jPLoginAbajo.add(jBIniciarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jlLoginAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGIN_INGRESO.png"))); // NOI18N
        jlLoginAbajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlLoginAbajoMouseClicked(evt);
            }
        });
        jPLoginAbajo.add(jlLoginAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 270));

        getContentPane().add(jPLoginAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, -240, 250, 270));

        jpFondo.setOpaque(false);
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLPublicidadSecundaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPublicidadSecundaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publi2.png"))); // NOI18N
        jpFondo.add(jLPublicidadSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 1000, 330));

        jLPublicidadPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPublicidadPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publi1.png"))); // NOI18N
        jpFondo.add(jLPublicidadPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 330));

        jLRayabaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paloPublic.png"))); // NOI18N
        jpFondo.add(jLRayabaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1000, 10));

        jLRayaAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paloPublic.png"))); // NOI18N
        jpFondo.add(jLRayaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        jBRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BACK.png"))); // NOI18N
        jBRegresar.setBorder(null);
        jBRegresar.setBorderPainted(false);
        jBRegresar.setContentAreaFilled(false);
        jBRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRegresarMouseClicked(evt);
            }
        });
        jpFondo.add(jBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, -1, 30));

        jBSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NEXT.png"))); // NOI18N
        jBSiguiente.setBorder(null);
        jBSiguiente.setBorderPainted(false);
        jBSiguiente.setContentAreaFilled(false);
        jBSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSiguienteMouseClicked(evt);
            }
        });
        jpFondo.add(jBSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 30));

        getContentPane().add(jpFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, 30));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Delete_32px.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 30));

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        getContentPane().add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSiguienteMouseClicked
        AnimationClass jBSiguientePrincipal = new AnimationClass();
        jBSiguientePrincipal.jLabelXRight(-1000, 0, 25, 5, jLPublicidadPrincipal);
        
        AnimationClass jBSiguienteSecundario = new AnimationClass();
        jBSiguienteSecundario.jLabelXRight(0, 1000, 25, 5, jLPublicidadSecundaria);
        
    }//GEN-LAST:event_jBSiguienteMouseClicked

    private void jBRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegresarMouseClicked
        AnimationClass jBSiguientePrincipal = new AnimationClass();
        jBSiguientePrincipal.jLabelXLeft(0, -1000, 25, 5, jLPublicidadPrincipal);
        
        AnimationClass jBSiguienteSecundario = new AnimationClass();
        jBSiguienteSecundario.jLabelXLeft(1000, 0, 25, 5, jLPublicidadSecundaria);
    
    }//GEN-LAST:event_jBRegresarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimationClass jBSiguientePrincipal = new AnimationClass();
        jBSiguientePrincipal.jLabelXLeft(0, -1000, 25, 5, jLPublicidadPrincipal);
        
        AnimationClass jBSiguienteSecundario = new AnimationClass();
        jBSiguienteSecundario.jLabelXLeft(1000, 0, 25, 5, jLPublicidadSecundaria);
     
    }//GEN-LAST:event_formWindowOpened

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizarMouseClicked
        this.setState(DiseñoDeSistemaAnimado.ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jlLoginAbajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLoginAbajoMouseClicked
        slider.jPanelYAbajo(-240, 0, 25, 5, jPLoginAbajo);
        slider.jPanelYArriba(0, -240, 25, 5, jPLoginAbajo);
    }//GEN-LAST:event_jlLoginAbajoMouseClicked

    private void jtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioActionPerformed

    private void jBIniciarSecionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIniciarSecionMouseClicked
        jtxtUsuario.setText("");
        jtxtContraceña.setText("");
        
        if(jtxtUsuario.getText() == "" && jtxtContraceña.getText() == ""){
            JOptionPane.showMessageDialog(null, "Usuario invalido");
        }
        else{
            Inicio inicio = new Inicio();
        }
    }//GEN-LAST:event_jBIniciarSecionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseñoDeSistemaAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseñoDeSistemaAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseñoDeSistemaAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseñoDeSistemaAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseñoDeSistemaAnimado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciarSecion;
    private javax.swing.JButton jBNuevoUsuario;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLPublicidadPrincipal;
    private javax.swing.JLabel jLPublicidadSecundaria;
    private javax.swing.JLabel jLRayaAlta;
    private javax.swing.JLabel jLRayabaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPLoginAbajo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlLoginAbajo;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPasswordField jtxtContraceña;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
