/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginconherramientas;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
/**
 *
 * @author Genarogg
 */
public class LoginConHerramientas extends javax.swing.JFrame {

    /**
     * Creates new form LoginConHerramientas
     */
    public LoginConHerramientas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLinternet = new javax.swing.JLabel();
        jLmusica = new javax.swing.JLabel();
        jLcalculadora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLNotas = new javax.swing.JLabel();
        jLPrograma = new javax.swing.JLabel();
        jLDrive = new javax.swing.JLabel();
        jLCronograma = new javax.swing.JLabel();
        jLSociedad = new javax.swing.JLabel();
        jLHerramientas = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jPIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jPIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Contraseña:");
        jPIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 180, 40));

        jLabel2.setBackground(new java.awt.Color(238, 112, 82));
        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("Usuario:");
        jPIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_User_96px_2.png"))); // NOI18N
        jPIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, 80));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField1.setText("ingresar usuario");
        jTextField1.setBorder(null);
        jPIngreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 180, 30));
        jPIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 210, 20));
        jPIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(0, 102, 102));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPIngreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 180, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Key_32px.png"))); // NOI18N
        jPIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_customer_32px_1.png"))); // NOI18N
        jPIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 30, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 40));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/Enter_OFF.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/Enter_ON.png"))); // NOI18N
        jToggleButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/Enter_ON.png"))); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/Enter_ON.png"))); // NOI18N
        jPIngreso.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 120, 30));

        jLinternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Globe_32px.png"))); // NOI18N
        jLinternet.setText("jLabel20");
        jLinternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLinternetMouseClicked(evt);
            }
        });
        jPIngreso.add(jLinternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 65, 30, 30));

        jLmusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Musical_Notes_32px.png"))); // NOI18N
        jLmusica.setText("jLabel20");
        jPIngreso.add(jLmusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 105, 30, 30));

        jLcalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Calculator_32px.png"))); // NOI18N
        jLcalculadora.setText("jLabel20");
        jLcalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcalculadoraMouseClicked(evt);
            }
        });
        jPIngreso.add(jLcalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 145, 30, 30));

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(238, 112, 82));
        jLabel13.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 112, 82));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Programa");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 180, -1, -1));

        jLabel14.setBackground(new java.awt.Color(238, 112, 82));
        jLabel14.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 112, 82));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cronograma");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel15.setBackground(new java.awt.Color(238, 112, 82));
        jLabel15.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 112, 82));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Herramientas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel16.setBackground(new java.awt.Color(238, 112, 82));
        jLabel16.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Notas ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jLabel17.setBackground(new java.awt.Color(238, 112, 82));
        jLabel17.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Drive");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel18.setBackground(new java.awt.Color(238, 112, 82));
        jLabel18.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 112, 82));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Sociedad");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Idea_96px.png"))); // NOI18N
        jLNotas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLNotasMouseMoved(evt);
            }
        });
        jLNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLNotasMouseExited(evt);
            }
        });
        jPanel1.add(jLNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, 150));

        jLPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Today_96px.png"))); // NOI18N
        jLPrograma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLProgramaMouseMoved(evt);
            }
        });
        jLPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLProgramaMouseExited(evt);
            }
        });
        jPanel1.add(jLPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 150));

        jLDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Google_Drive_96px.png"))); // NOI18N
        jLDrive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLDriveMouseMoved(evt);
            }
        });
        jLDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLDriveMouseExited(evt);
            }
        });
        jPanel1.add(jLDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 150));

        jLCronograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Clock_96px.png"))); // NOI18N
        jLCronograma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLCronogramaMouseMoved(evt);
            }
        });
        jLCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCronogramaMouseExited(evt);
            }
        });
        jPanel1.add(jLCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 150, 150));

        jLSociedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSociedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Handshake_96px.png"))); // NOI18N
        jLSociedad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLSociedadMouseMoved(evt);
            }
        });
        jLSociedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLSociedadMouseExited(evt);
            }
        });
        jPanel1.add(jLSociedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 150, 150));

        jLHerramientas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Maintenance_96px.png"))); // NOI18N
        jLHerramientas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLHerramientasMouseMoved(evt);
            }
        });
        jLHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLHerramientasMouseExited(evt);
            }
        });
        jPanel1.add(jLHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 150, 150));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(238, 112, 82));
        jTextField2.setText(" Buscar");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 150, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Multiply_32px.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginconherramientas/img/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
            
            AnimationClass internetRight = new AnimationClass();
            internetRight.jLabelXRight(-40, 20, 11, 6, jLinternet);
            
            AnimationClass internetLeft = new AnimationClass();
            internetLeft.jLabelXLeft(20, -40, 11, 6, jLinternet);
            
            AnimationClass musicaRight = new AnimationClass();
            musicaRight.jLabelXRight(-40, 20, 13, 5, jLmusica);
            
            AnimationClass musicaLeft = new AnimationClass();
            musicaLeft.jLabelXLeft(20, -40, 13, 5, jLmusica);
            
            AnimationClass calculadoraRight = new AnimationClass();
            calculadoraRight.jLabelXRight(-40, 20, 15, 4, jLcalculadora);
            
            AnimationClass calculadoraLeft = new AnimationClass();
            calculadoraLeft.jLabelXLeft(20, -40, 15, 4, jLcalculadora);
            
            
            
           
            
        
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.setState(LoginConHerramientas.ICONIFIED);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLProgramaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProgramaMouseMoved
        jLPrograma.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLProgramaMouseMoved

    private void jLProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProgramaMouseExited
        jLPrograma.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLProgramaMouseExited

    private void jLCronogramaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCronogramaMouseMoved
        jLCronograma.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLCronogramaMouseMoved

    private void jLCronogramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCronogramaMouseExited
        jLCronograma.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLCronogramaMouseExited

    private void jLHerramientasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHerramientasMouseMoved
        jLHerramientas.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLHerramientasMouseMoved

    private void jLHerramientasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHerramientasMouseExited
        jLHerramientas.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLHerramientasMouseExited

    private void jLNotasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNotasMouseMoved
        jLNotas.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLNotasMouseMoved

    private void jLNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNotasMouseExited
        jLNotas.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLNotasMouseExited

    private void jLDriveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLDriveMouseMoved
        jLDrive.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLDriveMouseMoved

    private void jLDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLDriveMouseExited
        jLDrive.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLDriveMouseExited

    private void jLSociedadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSociedadMouseExited
        jLSociedad.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
    }//GEN-LAST:event_jLSociedadMouseExited

    private void jLSociedadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSociedadMouseMoved
        jLSociedad.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
    }//GEN-LAST:event_jLSociedadMouseMoved

    private void jLinternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLinternetMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No Funciona", "LoginConHerramientas", 1);
        }
    }//GEN-LAST:event_jLinternetMouseClicked

    private void jLcalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcalculadoraMouseClicked
        Runtime rt = Runtime.getRuntime();
        try {
            Process p = rt.exec("calc");
            p.waitFor();
            
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No Funciona", "LoginConHerramientas", 1);
        }
        catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "No Funciona", "LoginConHerramientas", 1);
        }
    }//GEN-LAST:event_jLcalculadoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginConHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginConHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginConHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginConHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginConHerramientas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCronograma;
    private javax.swing.JLabel jLDrive;
    private javax.swing.JLabel jLHerramientas;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JLabel jLPrograma;
    private javax.swing.JLabel jLSociedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLcalculadora;
    private javax.swing.JLabel jLinternet;
    private javax.swing.JLabel jLmusica;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
