/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Genarogg
 */
public class Dock extends javax.swing.JDialog {

    int xMouse;
    int yMouse;
    public Dock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        int anchoDePantalla = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 289;
        this.setLocation(anchoDePantalla, 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLYoutube = new javax.swing.JLabel();
        JLTwiter = new javax.swing.JLabel();
        JLVisualStudioCode = new javax.swing.JLabel();
        JLWord = new javax.swing.JLabel();
        JLFacebook = new javax.swing.JLabel();
        JLCalculadora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLYoutube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/youtube_off.png"))); // NOI18N
        JLYoutube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLYoutubeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLYoutubeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLYoutubeMouseReleased(evt);
            }
        });
        getContentPane().add(JLYoutube, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 50));

        JLTwiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/twitter_off.png"))); // NOI18N
        JLTwiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLTwiterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLTwiterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLTwiterMouseReleased(evt);
            }
        });
        getContentPane().add(JLTwiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 50));

        JLVisualStudioCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/visualstudio_off.png"))); // NOI18N
        JLVisualStudioCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLVisualStudioCodeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLVisualStudioCodeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLVisualStudioCodeMouseReleased(evt);
            }
        });
        getContentPane().add(JLVisualStudioCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 50));

        JLWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/word_off.png"))); // NOI18N
        JLWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLWordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLWordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLWordMouseReleased(evt);
            }
        });
        getContentPane().add(JLWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 50));

        JLFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/facebook_off.png"))); // NOI18N
        JLFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLFacebookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLFacebookMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLFacebookMouseReleased(evt);
            }
        });
        getContentPane().add(JLFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));

        JLCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calculator_off.png"))); // NOI18N
        JLCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLCalculadoraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLCalculadoraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLCalculadoraMouseReleased(evt);
            }
        });
        getContentPane().add(JLCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/background.png"))); // NOI18N
        jLabel2.setText("JLabelBackgrounds");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 578, 72));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLFacebookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLFacebookMouseReleased
        ImageIcon fb = new ImageIcon(getClass().getResource("/img/facebook_off.png"));
        JLFacebook.setIcon(fb);
    }//GEN-LAST:event_JLFacebookMouseReleased

    private void JLFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLFacebookMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("www.facebook.com"));
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, evt);
        }
    }//GEN-LAST:event_JLFacebookMouseClicked

    private void JLFacebookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLFacebookMousePressed
        ImageIcon jLFace = new ImageIcon(getClass().getResource("/Img/facebook_on.png"));
        JLFacebook.setIcon(jLFace);
    }//GEN-LAST:event_JLFacebookMousePressed

    private void JLYoutubeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLYoutubeMousePressed
        ImageIcon jLYou = new ImageIcon(getClass().getResource("/Img/youtube_on.png"));
        JLYoutube.setIcon(jLYou);
    }//GEN-LAST:event_JLYoutubeMousePressed

    private void JLYoutubeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLYoutubeMouseReleased
        ImageIcon jLYou = new ImageIcon(getClass().getResource("/Img/youtube_off.png"));
        JLYoutube.setIcon(jLYou);
    }//GEN-LAST:event_JLYoutubeMouseReleased

    private void JLTwiterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLTwiterMousePressed
        ImageIcon jLTwi = new ImageIcon(getClass().getResource("/Img/twitter_on.png"));
        JLTwiter.setIcon(jLTwi);
    }//GEN-LAST:event_JLTwiterMousePressed

    private void JLVisualStudioCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLVisualStudioCodeMousePressed
        ImageIcon jLVisual = new ImageIcon(getClass().getResource("/Img/visualstudio_on.png"));
        JLVisualStudioCode.setIcon(jLVisual);
    }//GEN-LAST:event_JLVisualStudioCodeMousePressed

    private void JLCalculadoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLCalculadoraMousePressed
        ImageIcon jLCal = new ImageIcon(getClass().getResource("/Img/calculator_on.png"));
        JLCalculadora.setIcon(jLCal);
    }//GEN-LAST:event_JLCalculadoraMousePressed

    private void JLWordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLWordMousePressed
        ImageIcon jLWor = new ImageIcon(getClass().getResource("/Img/word_on.png"));
        JLWord.setIcon(jLWor);
    }//GEN-LAST:event_JLWordMousePressed

    private void JLTwiterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLTwiterMouseReleased
        ImageIcon jLTwi = new ImageIcon(getClass().getResource("/Img/twitter_off.png"));
        JLTwiter.setIcon(jLTwi);
    }//GEN-LAST:event_JLTwiterMouseReleased

    private void JLVisualStudioCodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLVisualStudioCodeMouseReleased
        ImageIcon jLVisual = new ImageIcon(getClass().getResource("/Img/visualstudio_off.png"));
        JLVisualStudioCode.setIcon(jLVisual);
    }//GEN-LAST:event_JLVisualStudioCodeMouseReleased

    private void JLCalculadoraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLCalculadoraMouseReleased
        ImageIcon jLCal = new ImageIcon(getClass().getResource("/Img/calculator_off.png"));
        JLCalculadora.setIcon(jLCal);
    }//GEN-LAST:event_JLCalculadoraMouseReleased

    private void JLWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLWordMouseReleased
        ImageIcon jLWor = new ImageIcon(getClass().getResource("/Img/word_off.png"));
        JLWord.setIcon(jLWor);
    }//GEN-LAST:event_JLWordMouseReleased

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void JLYoutubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLYoutubeMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("www.youtube.com"));
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, evt);
        }
    }//GEN-LAST:event_JLYoutubeMouseClicked

    private void JLTwiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLTwiterMouseClicked
        try{
            Desktop.getDesktop().browse(URI.create("www.twitter.com"));
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_JLTwiterMouseClicked

    private void JLVisualStudioCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLVisualStudioCodeMouseClicked
        try{
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("C:\\Users\\Genarogg\\AppData\\Local\\Programs\\Microsoft VS Code\\code.exe");
            p.waitFor();
        }
        catch(IOException e ){
            JOptionPane.showMessageDialog(this, e);
        }
        catch (InterruptedException ex) {
            Logger.getLogger(Dock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JLVisualStudioCodeMouseClicked

    private void JLCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLCalculadoraMouseClicked
        try{
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_JLCalculadoraMouseClicked

    private void JLWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLWordMouseClicked
        try{
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("C:\\Program Files\\Microsoft Office\\office16\\WIWORD.exe");
            p.waitFor();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "No funciona en este momento", "RocketDock", 0);
        }
        catch (InterruptedException ex) {
            Logger.getLogger(Dock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JLWordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dock dialog = new Dock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLCalculadora;
    private javax.swing.JLabel JLFacebook;
    private javax.swing.JLabel JLTwiter;
    private javax.swing.JLabel JLVisualStudioCode;
    private javax.swing.JLabel JLWord;
    private javax.swing.JLabel JLYoutube;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
